ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Arneburg par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Arnis par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Freital par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Garding par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Aub par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Bad Rappenau par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Bassum par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Bernsdorf (Oberlausitz) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Biesenthal par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Braeunlingen par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Burglengenfeld par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Burgstaedt par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Boennigheim par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Buerstadt par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Eibelstadt par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Engen par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Germering par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Ginsheim-Gustavsburg par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Grebenstein par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Hartenstein (Sachsen) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Hartha par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Hayingen par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Heiligenhafen par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Herbolzheim par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Herrien par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Hessisch Olndorf par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Hohenleuben par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Iphofen par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Klingenthal par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Kranichfeld par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Lauchhammer par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Lauda-Koenigshofen par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Lauta par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Lommatzsch par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Ludwigsstadt par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Moeckmuehl par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Muellrose par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Muensingen (Wuerttemberg) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Neuenstein (Hohenlohe) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Oelsnitz/Vogtl. par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Ornbau par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Pohlheim par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Polch par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Quakenbrueck par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Rauenberg par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Roemhild par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Roethenbach an r Pegnitz par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Scheinfeld par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Stadthagen par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Storkow (Mark) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Sulingen par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Taunusstein par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Uebigau-Wahrenbrueck par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Ulrichstein par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Vacha par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Viernheim par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Vilsbiburg par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Waldkirchen par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Wallduern par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Weismain par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Welzheim par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Werr (Havel) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Wiesensteig par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Winsen (Luhe) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Woerth an r Donau par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Ziegenrueck par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Ziesar par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Auma-Weidatal par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Bueren (Westfalen) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Erlenbach am Main par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Falkenstein/Harz par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Schoenberg (Mecklenburg) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Belgern-Schildau par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Leipzig par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Bruehl (Rheinland) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Koenigstein (Saechsische Schweiz) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Koenigstein im Taunus par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Oranienbaum-Woerlitz par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Borgentreich par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Cochem par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Dorsten par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Drolshagen par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Elsdorf (Rheinland) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Erbendorf par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Finsterwal par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Glin par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Haigerloch par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Hettstedt par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Hochheim am Main par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Lennestadt par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Lichtenau (Westfalen) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Loewenstein par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Luenen par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Nettetal par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Orberg par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Rees par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Regen (Stadt) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Rehburg-Loccum par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Rheinau (Ban) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Spenge par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Tegernsee (Stadt) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Telgte par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Tirschenreuth par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Wildberg (Schwarzwald) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Siebenlehn par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Friedrichshafen par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Greifswald par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Marburg par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Rendsburg par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Wismar par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Aken (Elbe) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Amberg par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Bad Blankenburg par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Barntrup par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Bismark (Altmark) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Bocholt par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Bueckeburg par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Celle par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open litzsch par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Eberswal par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Ellwangen (Jagst) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Eschborn par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Freising par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Gladbeck par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Goslar par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Gotha par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Ingelheim am Rhein par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Iserlohn par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Juelich par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Koethen (Anhalt) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Lindau (Bonsee) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Lueg par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Marktbreit par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Nidda par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Passau par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Plettenberg par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Saarburg par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Unterschleissheim par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Weener par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Wittenburg par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Altenkirchen (Westerwald) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Amorbach par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Arnstadt par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Bad Pyrmont par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Bergneustadt par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Bernburg (Saale) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Blaubeuren par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open ggendorf par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open mmin par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Donaueschingen par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Ebersberg par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Frankenthal (Pfalz) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Geretsried par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Gross-Umstadt par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Haan par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Hueckeswagen par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Kirchen (Sieg) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Leinefel-Worbis par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Muennerstadt par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Oberhof par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Penzberg par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Plauen par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Riedlingen par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Sarstedt par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Strehla par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Warendorf par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Wein in r Oberpfalz par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Wiesmoor par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Zirndorf par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Zittau par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Krakow am See par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Waren (Mueritz) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Ronberg par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Schesslitz par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Themar par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Veln (Pegnitz) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Borken (Hessen) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Nassau (Lahn) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Neustadt am Kulm par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Titisee-Neustadt par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Weissenburg in Bayern par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Jerichow par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Frauenstein (Erzgebirge) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Kirchberg (Sachsen) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Neuenburg am Rhein par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Olpe par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Oberharz am Brocken par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Raguhn-Jessnitz par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Suedliches Anhalt par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Roettenbach (bei Erlangen) par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Hessisch Lichtenau par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Anau par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Kirn par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Kreuztal par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Netphen par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Rheinsberg par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Unkel par_close brack_close
ask where brack_open var_c rdf_type dbo_Town sep_dot var_c dbo_country dbr_Germany sep_dot var_c rdfs_label par_open Pockau-Lengefeld par_close brack_close
