<unk>
<s>
</s>
Loeffingen
Erding
Langenburg
Nauen
Gefell
Reichenhall
Querfurt
par_close
Neukirchen
Geisingen
Borna
Felsberg
Rostock)
Buchen
Eberbach
Linz
Calbe
Rappenau
Waldkirchen
Ehingen
Berka/Werra
Schesslitz
Krempe
Alsdorf
Koenigsee-Rottenbach
Eltmann
Kirchhunm
Muehldorf
Franzburg
Gummersbach
Goch
(Uckermark)
Witzenhausen
Talheim
Anklam
Dueren
Burgwel
Marlow
Sarstedt
Mebach
Leinefel-Worbis
Waiblingen
Netzschkau
Ortrand
Hercke
Niesky
Rastenberg
Scheinfeld
Eislingen/Fils
(Zollernalbkreis)
Sangerhausen
Luckenwal
Leonberg
Roethenbach
Plettenberg
Fichtelgebirge
Buckow
Wolfenbuettel
Tirschenreuth
Soon-Allendorf
Bretten
Suhl
Prichsenstadt
Gruensfeld
Allstedt
Neresheim
Clausthal-Zellerfeld
Koenigslutter
Lehrte
Bingen
Celle)
Syke
Koelleda
Tambach-Dietharz
Pyrmont
Tanna
Lunzenau
Wesenberg
Wehr
Bentheim
Ilm
Lanburg
Wuerselen
Dannenberg
Mosbach
Kalbe
Neckargemuend
Schwaigern
Weiterstadt
Hoechstaedt
Walnbuch
Borken
Wettin-Loebejuen
(Leine)
Stoessen
Olnburg
Dillingen/Saar
Waltrop
Allendorf
Schoenwald
Schandau
Teuschnitz
Pinneberg)
Horn-Bad
Reinfeld
Alsleben
Kremmen
Koestritz
Brannburg
Gaildorf
Schwarzenbach
Rennweg
Koenigsbrueck
Egeln
Meiningen
Rhoen
Ebersberg
Lauterberg
Preussisch
Schmalkaln
Alsfeld
Dassow
Selbitz
Schoenebeck
Koethen
Homburg
Ziegenrueck
Teltow
Burgstaedt
Koetzting
Niemegk
(Salzach)
Haltern
Schussenried
Glanbach
Neuenhaus
Nabburg
Selters
Kuehlungsborn
Hemmingen
Haiger
Gmuend
Altena
Hatzfeld
Ravormwald
Renningen
Homberg
Altlandsberg
Storkow
Ellrich
(Ruhr)
Rieneck
Dahme/Mark
Kirchenlamitz
Zahna-Elster
Parsberg
Schwalbach
Stadtlengsfeld
Donauwoerth
Luetzen
Tornesch
Ruesheim
Buergel
Herdorf
Florstadt
Boizenburg/Elbe
Fulda
Naumburg
Greussen
Lambrecht
Griesheim
Dorfen
Hoenningen
Mesche
Trenlburg
Belzig
Rockenhausen
Sachsenhagen
Asperg
Weissenhorn
Falkenstein/Vogtl.
Lommatzsch
Ratingen
Leer
Cham
Mergentheim
Dingelstaedt
Altenburg
Gnoien
Osterfeld
Weinstrasse
Kaiserstuhl
Ilmenau
Messkirch
Hamminkeln
(Wuerttemberg)
Eisfeld
bei
Gotha
Gifhorn
Hornbach
Teuchern
Gefrees
Babenhausen
Buerstadt
Harz
Elsterberg
Plochingen
Raunheim
Luckau
Hohenberg
Ludwigsfel
Putlitz
Bergen
Greiz
Lahnstein
Ribnitz-Damgarten
Tengen
Hausach
Havel
Warendorf
Eger
(Lahn)
Spalt
(Landkreis
Graefenberg
Amberg
Forchtenberg
Langenhagen
Finsterwal
Werneuchen
Velten
Halberstadt
Grafing
Barby
Neustadt
Cuxhaven
Seelze
Nornham
Uhingen
Gau-Algesheim
Boxberg
Jerichow
Soltau
Schleiz
Kirchheimbolann
Wittstock/Dosse
Dingolfing
Marl
Jork
Miesbach
Weissenthurm
Moelln
Moeckern
(Kyffhaeuser)
(Sieg)
Bernau
Papenburg
Waltershausen
Lauenburg/Elbe
(Nierrhein)
Breuberg
Lausick
Bismark
Gross-Gerau
Rosenfeld
(Thueringen)
Joehstadt
Solms
Oberwesel
Friedberg
Erbach
Rees
Lugau/Erzgeb.
Lindschied
Rosbach
Bayreuth
Rehau
Marne
Heick
an
Bonndorf
Angermuen
Wildbad
Brake
Oer-Erkenschwick
Fuerstenberg/Havel
(Ohm)
Wiesental
Arneburg
Ronneburg
Rhein
(Region
Winsen
Friesoythe
Gross-Umstadt
Kirn
Velbert
Loeningen
Luebben
Tuebingen
Hann.
Pfullingen
Wilhelmshaven
Alfeld
Obernburg
Lohr
Schirgiswal-Kirschau
Neuhaus
Aisch
Huenfeld
Geretsried
Baruth/Mark
Ramstein-Miesenbach
Frankenhausen/Kyffhaeuser
Wolmirstedt
Plattling
Lich
Usedom
Artern/Unstrut
Rahn
Tharandt
Salzkotten
Teinach-Zavelstein
Oberlungwitz
Wertheim
Altoetting
Kissingen
Naila
Gersfeld
Haslach
Bersenbrueck
Lohne
(Knuell)
Rottweil
Eltville
Wilshausen
Hitzacker
ueberlingen
Neumarkt
Stargard
Schoeppenstedt
Kamen
Halle
Thalheim/Erzgeb.
Otterberg
Liebstadt
Dornstetten
Staffelstein
Eibenstock
Unkel
Usingen
where
(Iller)
Wendlingen
(Onwald)
Magburg)
Stromberg
Offenburg
Hennigsdorf
Rheinberg
Seligenstadt
Gera
Biesenthal
Duerkheim
Neuss
Wustrow
Spaichingen
Wildberg
Steinbach
Dietfurt
Donaueschingen
Wel
Gebesee
Neukloster
Neukirchen-Vluyn
Ostfilrn
Neustrelitz
Vohenstrauss
Suessen
Geisenheim
Bendorf
Hessdorf
Friedrichshall
Strehla
Oranienburg
Roermark
Rheda-Wienbrueck
Nachrodt-Wiblingwer
Zwiesel
Lahn
Koenigshofen
Pfullendorf
Eisenberg
Braeunlingen
Schotten
Loehne
Ulrichstein
Laufen
Hei
Stendal
Lengerich
Burgau
Rottenburg
Krautheim
Mittweida
Muenchenbernsdorf
Bogen
Winnenn
Schwentinental
Stralsund
Ingelheim
Durstadt
Geislingen
Glueckstadt
(Mueritz)
Geisa
(Oberfranken)
Cottbus
Wissen
Meinerzhagen
Rheinstetten
Starnberg
Dietenheim
Hettingen
vor
Eisleben
(Pfalz)
Uttenreuth
Stadt
Lauchhammer
(Sachsen)
Germersheim
Grossroehrsdorf
Freienwal
Scheer
Geiselhoering
Fallingbostel
Waldkappel
Elsterwerda
Koennern
Wolgk
Wyk
Heilberg
Arendsee
Langenfeld
Lingen
Trossingen
Ornbau
Drebkau
Gaggenau
Gladbach
Heiligenhafen
Lucka
Bamberg
Enkoben
(Oberlausitz)
Ellingen
Hennef
(Holstein)
Glashuette
Bebra
Stolberg
Senn
Grossbottwar
Hirschberg
Bruchkoebel
Rotenburg
Pocking
Oberasbach
Ummerstadt
Furth
Nordhorn
Mengen
Veringenstadt
Rheinsberg
Heinsberg
Grafenau
Kohren-Sahlis
Toenning
Kuelsheim
Ochtrup
Erlangen)
Langen
Ludwigsburg
Freital
Tamm
Muensingen
Forst
Oberviechtach
(Mecklenburg)
Ruppichteroth
Wilsnack
Knittlingen
Leichlingen
Wriezen
Weikersheim
Elster
Liebenwerda
Grebenstein
Lorch
Wiesban
Gevelsberg
Bernsdorf
Ditzingen
Herzogenrath
Remda-Teichel
Elterlein
Memmingen
Doebern
Schoemberg
Troisdorf
Fuerstenwal/Spree
Iburg
Haseluenne
Osthofen
Goldberg
Winterberg
Kirchen
Waldmuenchen
Grossenhain
Saale
Grossbreitenbach
in
Diepholz
Heppenheim
Lueg
Giengen
Schriesheim
Lieberose
Woerrstadt
Erkner
Laubach
Moeckmuehl
Neuoetting
Bergneustadt
Bernkastel-Kues
Wilkau-Hasslau
Kranichfeld
Freyburg
Gerlingen
Ruebenberge
Sachsenheim
Bexbach
Oberkirch
Beverungen
Friedrichroda
Wirges
Wilthen
Muskau
Ballenstedt
litzsch
Gerbstedt
Guetzkow
Mechernich
Grimmen
Georgen
Friedrichshafen
Herrien
Eisenach
Sinzig
Frankfurt
Neubrannburg
Ruethen
Neckarsteinach
Floersheim
Halnsleben
Frankenberg
Heringen
Friedrichsthal
Werdau
Wurzbach
Schleswig
Duerrheim
Kemberg
Hoexter
Bibra
Anrnach
Kulm
Windsheim
Cloppenburg
Lichtenberg
Bargtehei
Lueneburg
Hochheim
(Wendland)
Colberg-Heldburg
Berleburg
Unterschleissheim
Stadtallendorf
Lech
Schoeningen
Hoechstadt
Heubach
Segeberg
Pinneberg
Neubulach
Reichenbach/O.L.
(Havel)
Schraplau
Muenzenberg
Kitzingen
Waghaeusel
Inn
Freunberg
Schelklingen
Muellrose
Hoehe
Leutenberg
Kanrn
Schlotheim
Euskirchen
Duelmen
Nordwal
Rosenthal
Breisach
Penzlin
Gunzenhausen
(Hegau)
Osterwieck
Friedland
Kleve
Quickborn
Oppenheim
Karlshafen
(Hohentwiel)
(Gemein)
Ebermannstadt
Schneverdingen
Weinstadt
Neuffen
Brottero-Trusetal
Elsfleth
Kaltennordheim
Griesbach
Bassum
Crimmitschau
Noerdlingen
Teutoburger
Muenchberg
Guetersloh
Vellberg
Lauchstaedt
Nordhei
Neuenburg
Schwandorf
Warstein
Waldkirch
Pfaffenhofen
Lychen
Zell
Waren
Wolgast
Jever
Allgaeu
Nossen
Kastellaun
Hof
(Nierbayern)
Nassau
ttelbach
Steinfurt
Hadamar
Vlotho
Dueben
Heimsheim
Norrney
Goerlitz
Joachimsthal
Tegernsee
Goarshausen
Honnef
(Wohra)
Zeil
Grevenbroich
Eckernfoer
Weinheim
Augustin
Herrenalb
Plau
Gruenstadt
Nienstein
Arnstein
Wangen
Stutensee
Georgsmarienhuette
Wipperfuerth
Recke
Brandis
Minlheim
Sulzbach/Saar
Muencheberg
Auerbach/Vogtl.
Hofgeismar
Beilstein
Twistringen
Zweibruecken
Linn
Zeulenroda-Triebes
Dorsten
Neuenstein
(Eifel)
Wittingen
Rietberg
Brackenheim
Melsungen
Gelnhausen
Zeitz
Wilsdruff
Voehringen
Neckar
Steinbach-Hallenberg
Salztfurth
Kanl
Taucha
Ebeleben
Spremberg
(Niersachsen)
Oelsnitz/Erzgeb.
Stassfurt
Juelich
Altentreptow
Lauterecken
Wasserburg
Monheim
Fuerstenfeldbruck
Dachau
Weingarten
Brocken
Breisgau
Frankenthal
Fuessen
Raberg
Wiesloch
Buttstaedt
Pritzwalk
Moers
(Sachsen-Anhalt)
Drolshagen
Wittenberge
(Aller)
Waldnaab
Saarlouis
(Bo)
Schweiz)
Tann
Rosenheim
Schmieberg
Mittenwal
Steinheim
Gunlsheim
Garching
Fuerth
Markranstaedt
Remagen
Neuenra
Greifswald
Bremen
Harmersbach
Zwickau
Owen
Hargsen
Senftenberg
Schoenau
Kellinghusen
Peine
Unna
Westerste
Lichtenau
Berlin
Beelen
Grossalmero
See
Heilbad
Hagenbach
Loerrach
Ingolstadt
Laupheim
Bocholt
Furtwangen
Torgau
unter
Worms
Landshut
Wolkenstein
Gabusch
Gelrn
(Hunsrueck)
Wiesensteig
Camberg
Pockau-Lengefeld
ister
Wittlich
Melle
Hammelburg
Emstten
Achim
Schwarzenberg/Erzgeb.
Neunburg
Hornberg
Oberweissbach/Thueringer
Torgelow
Olsloe
(Saar)
Hohenleuben
Sulingen
Beeskow
(Schwarzwald)
Saerbeck
Kinlbrueck
Lemgo
Guben
Pegau
Malchin
Ploen
Borgentreich
Sulza
Altmuehl
(Ostsee)
Schnaittenbach
Kirchlengern
Idar-Oberstein
Doemitz
(Maerkische
Oberbayern
Nortorf
Hechingen
Moringen
Hagenow
Raguhn-Jessnitz
Hoerstel
Niggen
Toenisvorst
Erkrath
Herscheid
Koblenz
Hillesheim
Traunreut
Sinlfingen
Muenr
Everswinkel
Oschersleben
Lauchheim
Blankenburg
Kraichtal
Arnstadt
Gengenbach
Runkel
Rathenow
Wehlen
Kelheim
Weissenfels
Schwarzwald
Brenz
Roding
Gernsheim
Oranienbaum-Woerlitz
Dahlen
Pausa-Muehltroff
Woerth
Rabeul
Sonneberg
Aub
Pfreimd
Muegeln
Neuwied
Jarmen
Soemmerda
Schuettorf
Northeim
Wegberg
Treuen
Karben
Quakenbrueck
Ronberg
Berneck
Niernhall
Witten
Schwaebisch
Renchen
Bremervoer
Laucha
Emn
Unterfranken
Oeran
Osterholz-Scharmbeck
(Stadt)
Luebtheen
Konz
Heiligenstadt
Sesslach
Hohenmoelsen
ask
Boeblingen
uebach-Palenberg
Schneeberg
Schwaan
Kluetz
Meldorf
Sankt
Lohmar
Hueckelhoven
Waldheim
brack_open
Hiln
Illertissen
(Bayern)
Garding
Siebenlehn
Rathmannsdorf
Trochtelfingen
Widrn
Wernigero
Hildburghausen
Ohrdruf
Meinberg
Marktsteft
Nebra
Mendig
Schongau
Grossschirma
Porta
Herbolzheim
Wuennenberg
Raburg
Hoehr-Grenzhausen
Rochlitz
Luenscheid
Straubing
Freinsheim
Wenl
Schopfheim
Grebenau
Buehl
Isar
Thannhausen
Gern
Hofheim
Eppingen
Kulmbach
Stolpen
Sennhorst
Oberreichenbach
Sehn
Triptis
Amorbach
Huerth
Rheinbach
Ochsenfurt
Loebau
Alzenau
Nierkassel
Herten
Preetz
Ennepetal
Schlettau
Hoyerswerda
(Hessen)
Pulsnitz
Crailsheim
Anhalt
Weil
Lenzen
Pappenheim
Marktredwitz
isheim
Roebel/Mueritz
Marktheinfeld
Peitz
Hemmoor
Jessen
Ravensburg
Vern)
Schwarzenbek
Luenen
Dohna
Laage
Ottweiler
Burladingen
Ban-Ban
Itzehoe
Schweinfurt
Goessnitz
Foehr
Gueglingen
Wilnfels
Kevelaer
Saalfeld/Saale
r
Meissen
Harsewinkel
(Er)
Geisenfeld
Main
Bramsche
Reinbek
Hilchenbach
Jagst
Polch
Duerrenberg
Bischofswerda
Zerbst/Anhalt
(Efze)
Emmendingen
Freyung
Pressath
Oppenau
Nierstein
Wolfratshausen
Schoenewal
Gammertingen
Sta
(Mark)
Tauber
Muellheim
Scheibenberg
Grossenehrich
Schoenberg
Schluesselfeld
Berga/Elster
Walnburg
Trebsen/Mul
Gemuenn
Kappeln
Vellmar
Merkendorf
Sunrn
Tauberbischofsheim
Osnabrueck
Miltenberg
Dahn
Kreuznach
Kirtorf
Sontra
Oettingen
Mayen
Speyer
Hemau
Eberswal
Klingenthal
Vallendar
Waischenfeld
Barmstedt
Lichtenfels
(bei
Gerolzhofen
Giessen
Kirchhain
Haren
Simmern/Hunsrueck
Wittmund
Halver
Driburg
(Werra)
Heilbronn
Beelitz
Roemhild
Birkenfeld
Creussen
Lutherstadt
Grimma
Saalburg-Ebersdorf
Langensalza
Geesthacht
Wechselburg
(Unterweser)
Rheinau
Brueckenau
Montabaur
Sayda
Frohburg
Kroepelin
Hecklingen
Linnich
Pfalz
(Donau)
Finnentrop
Teterow
Herzogenaurach
Augustusburg
(Bergstrasse)
(Mosel)
Salzuflen
Rowisch
Olbernhau
Neustadt-Glewe
Kronberg
Stadtprozelten
Nuernberg
Welzow
Geseke
Oberndorf
Glin
Beilngries
(El)
Parborn
Buetzow
Kupferberg
Baesweiler
Arzberg
Dornburg-Camburg
Weisswasser/Oberlausitz
Roettenbach
Buedingen
Stadthagen
Burg
Aschersleben
Dierdorf
Oestrich-Winkel
Rhinow
Willich
Straelen
Eichstaett
Schillingsfuerst
Falkenstein/Harz
Main)
Ronnenberg
Vilshofen
Schortens
Schluechtern
Hainichen
Telgte
Ahaus
(Lumda)
Schlitz
Heitersheim
Linnberg
Ganrsheim
Volkmarsen
Freiburg
Schenefeld
Oelsnitz/Vogtl.
Bad
Lauscha
Saeckingen
Hermsdorf
Lollar
Soest
Kelbra
Gartz
Baiersdorf
Borgholzhausen
Weida
Lindow
Premnitz
Biberach
Treffurt
Bonwerr
Brunsbuettel
Goettingen
Ebern
(Saechsische
Crivitz
Rothenburg/Oberlausitz
Urach
Hersfeld
Kaiserslautern
Schwabmuenchen
Schwartau
Kyllburg
rdf_type
Hessisch
Castrop-Rauxel
Muenstermaifeld
Hohnstein
Grafenwoehr
Sassenberg
Putzbrunn
Wassertruedingen
Weissenburg
Engen
Muehlhausen/Thueringen
Simbach
Visselhoeve
Brakel
Boppard
(Westerwald)
Betzdorf
Ettenheim
Rauenberg
Leun
Uelzen
lbrueck
Belgern-Schildau
Hameln
Sulzburg
Seehausen
Schrobenhausen
Buckenhof
Liebenau
Selm
Lindau
Pruem
Haan
Rehburg-Loccum
Wahlstedt
Muehlheim
Dinkelsbuehl
(Unterfranken)
Waldshut-Tiengen
Burgdorf
Ingelfingen
Bischofsheim
Hemsbach
Mainburg
Suelze
Celle
Seeland
Spangenberg
Lippspringe
(Vogelsbergkreis)
Bayern
Braubach
Hockenheim
Blieskastel
Wachenheim
Kornwestheim
Billerbeck
Werl
Vilseck
Walsro
Ulm
Altdorf
Ravenstein
Weismain
(Olnburg)
Enzweihingen
Marienberg
Ostritz
Laufenburg
(Ostfriesland)
Thale
Loewenstein
Emmerich
Marktbreit
Kaufbeuren
Siegen
Pforzheim
Warn
Groeningen
Trifels
Hallenberg
Overath
Stadtilm
Falkensee
Falkenberg/Elster
Gernsbach
Grabow
Meyenburg
Herford
Oberriexingen
Hungen
Lauf
Kinzigtal
(Neckar)
Lauda-Koenigshofen
Eppstein
Willebassen
Erwitte
Fellbach
Teck
Roettingen
Ruegen
Marktleuthen
Pfarrkirchen
Luebbecke
Wesel
Eschershausen
Erftstadt
Bramstedt
Neckarbischofsheim
Dissen
Seesen
Buen
Wiehe
Cochem
Eisenhuettenstadt
Hidnhausen
Marienmuenster
Trostberg
Dransfeld
Zwenkau
Gruenhain-Beierfeld
Balve
Riss
Sobernheim
Arnsberg
Garz/Ruegen
Ems
Ingbert
Espelkamp
Uslar
Tangerhuette
Oeynhausen
Rottal
Spenge
Bergzabern
Rheine
Schwalmstadt
Garlegen
Eschweiler
Karlsruhe
Riedstadt
(Or)
dbo_Town
Buchholz
Ulmen
Gruenberg
Weener
Aschaffenburg
Velburg
Kierspe
Buelsdorf
Bitterfeld-Wolfen
Hohenstein-Ernstthal
Bergisch
Laatzen
Dinslaken
Burscheid
Johanngeorgenstadt
Altenkirchen
Hassfurt
Hirschhorn
Kalchreuth
oehringen
Isselburg
Neutraubling
(Westfalen)
Clingen
Neunkirchen
Hermeskeil
Hachenburg
Fridingen
Son-Salmuenster
Dieburg
Weilheim
Schoeneck/Vogtl.
Wolfstein
Mahlberg
Pasewalk
Kuenzelsau
Schramberg
Schorndorf
Wolfhagen
Pulheim
Wilnrath
(Spreewald)
Anau
Beerfeln
vorm
Brilon
lmenhorst
Freising
Weilburg
Bopfingen
(Rheingau)
Muenchen
Bienkopf
brack_close
Grossraeschen
Markdorf
Nauheim
Schlein
Enger
Waibstadt
Horb
Schoensee
Zoerbig
Zella-Mehlis
Netphen
Freystadt
Seelow
Oberwiesenthal
Dargun
Gross-Bieberau
Tecklenburg
(Harz)
Muehlacker
Ranis
Landau
Ansbach
Eggesin
Sonrshausen
Diemelstadt
Olndorf
Heilsbronn
Zehnick
Ichenhausen
Lichtenstein/Sa.
Nieheim
Lauta
Schwabach
Konstanz
Regen
Kyritz
Rodach
Kronach
Zwoenitz
Wismar
Bitburg
Gehrn
Diez
Gerolstein
Asslar
Schkoelen
Gladbeck
Olfen
Toelz
Amoeneburg
Burgbernheim
Walck
Lippstadt
Tuttlingen
Marburg
Muenn
Moerfeln-Walldorf
Nidrau
Veit
Klingenberg
Wenn
Weimar
(Duemmer)
Boennigheim
Nufringen
Bruchsal
Lorsch
Gronau
Neunau
Menn
Loitz
(Kreis
Neuendorf
Heilbronn)
Olpe
Schweich
auf
Leinfeln-Echterdingen
Hartenstein
Rheinfeln
Neuenbuerg
Parchim
Zittau
Ziesar
Nastaetten
Baunach
Altensteig
Kemnath
Regensburg
Holzminn
Neckarsulm
Wunsiel
Springe
Weissenberg
Roesrath
tmold
Koenigswinter
(Altmark)
Bornheim
Prenzlau
Oberursel
Perleberg
Alpirsbach
Xanten
Hattersheim
Berka
Steinach
Wittenburg
Rudolstadt
Tribsees
Viechtach
Olsberg
Husum
Salzungen
Guestrow
Rossleben
Stockach
Lienen
Pohlheim
Siegburg
Meckenheim
Munster
Germering
Nierstetten
Staufen
Ibbenbueren
(Steinburg)
Zirndorf
Bernburg
Seifhennersdorf
Schwarzhei
Tangermuen
Hettstedt
Sandau
Aalen
Wimpfen
Buchloe
Ratzeburg
Schwarzenhasel
Wesseling
im
Hattingen
Saarburg
Osterburg
Dippoldiswal
Leipheim
Meerbusch
Kirchberg
Kirchheim
Hall
Muecheln
Herzberg
Geringswal
Calau
Mainbernheim
Trebbin
Garbsen
Romrod
Annaburg
Schifferstadt
Wittichenau
Guenzburg
Zarrentin
Zwingenberg
Orberg
Frauenstein
Templin
Eschwege
Nierstotzingen
(Pegnitz)
Wein
Walldorf
Hayingen
Bueren
(Rheinland)
Sinsheim
Erkelenz
Hersbruck
Zuelpich
Holte-Stukenbrock
Niebuell
Liebenstein
Wurzach
Welzheim
Sulzbach-Rosenberg
Einbeck
Karlstadt
Salzwel
ssau-Rosslau
Aulendorf
Havelsee
Dornhan
Orb
Maerkisch
Heiligenhaus
Aibling
Werr
Teublitz
Immenhausen
(Luhe)
Mainz
Malchow
Rabenau
Viersen
Adorf/Vogtl.
Wassenberg
Kuppenheim
Rhe
Elm
Brueel
(Jagst)
Holstein
Ilsenburg
Ehrenfriersdorf
Vohburg
Betzenstein
Moehrendorf
Tessin
Riedlingen
(Sauerland)
Ketzin/Havel
Ransbach-Baumbach
Geestland
Stadtlohn
Nienburg
Remseck
(Unstrut)
(oertze)
(Siegerland)
Reichelsheim
Voehrenbach
Puettlingen
Rinteln
Groeditz
Langenzenn
Weinsberg
Greven
Strasburg
Steinau
Hollfeld
Osterburken
Treuenbrietzen
Oerlinghausen
Son
Eibelstadt
Wegeleben
Strasse
Donau
Braunsbedra
Richtenberg
Abensberg
sep_dot
Westerburg
Brueck
Neuerburg
Luebz
dbo_country
Ellwangen
Rendsburg
Liebenzell
Arnis
Iphofen
Buchau
Koenigs
(Nahe)
Warin
Grevesmuehlen
Elze
Hannover)
Minn
Koenigstein
Wasungen
Rothenfels
Blumberg
am
Otterndorf
Frankenberg/Sa.
Neumarkt-Sankt
Schleusingen
Limburg
Goslar
Moosburg
Schwedt/Or
Themar
Baernau
Lassan
Wildungen
Neubukow
Hanau
Heimbach
Baunatal
Greding
Butzbach
Wald
Stadtbergen
Ettlingen
Maintal
Kloetze
Schiltach
(Elster)
Werdohl
Hemer
Alsheim
Marloffstein
Hauzenberg
Murr
Braunfels
Maxhuette-Haidhof
Roental
Neuruppin
Stuttgart
Weissensee
Kaub
Sassnitz
Neu-Ulm
Eilenburg
Datteln
Damme
Goldkronach
Kitzscher
Geithain
Blasien
Mitterteich
Freilassing
Nienburg/Weser
Warburg
Fladungen
Aue
Freunstadt
Bueckeburg
Freiberg
Kempten
Bockenem
(Vogtland)
Erlenbach
Wesselburen
Pegnitz
Marktoberdorf
Muenstereifel
Saulgau
Murrhardt
Goeppingen
Schkeuditz
Leutershausen
Feuchtwangen
Weissenstadt
Jueterbog
Sonnewal
Korbach
Altenberg
Doebeln
Leipzig
Westfalica
Munrkingen
Rodalben
Wolframs-Eschenbach
Linnfels
Waldkraiburg
Meerane
Kroppenstedt
Lauterbach
Rerik
Vogtsburg
Wilster
Nenndorf
Nier-Olm
Stollberg/Erzgeb.
Oberkochen
Wernau
(Ems)
Dassel
dbr_Germany
Ludwigshafen
Auma-Weidatal
Calw
Vern
Eschborn
Lebus
Roth
Barsinghausen
Waldsassen
Auerbach
Oberhof
Markneukirchen
Coesfeld
Ebersbach-Neugersdorf
Pottenstein
St.
Eckartsberga
Hallstadt
Toeging
Vogtland
Hohen
Mellrichstadt
Passau
(Allgaeu)
Wallduern
Fuerstenau
Woerishofen
Penzberg
Barth
Waldsee
Bruessow
Haigerloch
Fehmarn
Unstrut
Leuna
(Ban)
Heinau
Taunus
Lebach
Pirmasens
(Rhoen)
Herbrechtingen
(Bonsee)
Obermoschel
Herrnhut
Vilbel
Sulz
Creuzburg
Suedliches
(Elbe)
Hoya
(Oberpfalz)
Roetha
Gerabronn
Sprockhoevel
Titisee-Neustadt
Tittmoning
Drensteinfurt
Kenzingen
Burglengenfeld
Bedburg
Heringen/Helme
Wittenberg
Goar
Idstein
Metzingen
Osterhofen
Aken
Haiterbach
Bergkamen
Muehlberg/Elbe
Reutlingen
Schaalsee
Havelberg
Ostero
Magdala
Lengenfeld
Bleichero
Nordhausen
Elsdorf
Erbendorf
Pattensen
Saarbruecken
Rienburg
Friesack
Elstra
Friedrichstadt
Braunlage
Zschopau
Werne
Blankenhain
ob
Pfungstadt
Eschenbach
Herborn
Neusalza-Spremberg
Krozingen
Burgkunstadt
Annaberg-Buchholz
Langenprozelten
Meppen
Coburg
Bexhoeve
Speicher
Langelsheim
Kusel
Wanzleben-Boer
Limbach-Oberfrohna
Bergheim
Balingen
Isny
Backnang
Hoetmar
Sanrsdorf-Brehna
Heinheim
Roetz
Uebigau-Wahrenbrueck
Ortenberg
Laichingen
Endingen
Varel
Burghausen
mmin
Genthin
Schwerin
Thum
Meuselwitz
Huefingen
Schwerte
Taunusstein
Dillenburg
Bredstedt
Selb
Herbstein
Kelsterbach
Spardorf
Grund
Gommern
Aichach
Schauenstein
oestringen
Rhens
Schnackenburg
Doberan
Dommitzsch
Alsberg
Filrstadt
(Mil)
Koenigsberg
Kerpen
Neuenstadt
Oberharz
Breisig
Breckerfeld
Bensheim
Boehlen
Schwelm
Dormagen
Kamp-Lintfort
Rutesheim
Neu-Anspach
Wolfsburg
Barntrup
Kempen
Doberlug-Kirchhain
Triberg
Muennerstadt
Alzey
Sebnitz
Graefenthal
Hueckeswagen
Mansfeld
Neukalen
Lauffen
Strausberg
(Westf.)
Orla
Luechow
Rauschenberg
Attendorn
Pleystein
Harzburg
Golssen
Korschenbroich
Uffenheim
Buxtehu
Wusterhausen
Hartha
Kelkheim
Wuelfrath
Bremerhaven
(Erzgebirge)
Volkach
Lampertheim
ggendorf
Langewiesen
Vechta
Kalkar
Rheinboellen
Plaue
Laaber
Ennigerloh
Oberpfalz
Frechen
(Wuemme)
Buttelstedt
Ludwigslust
Kreuztal
Colditz
(Hohenlohe)
Glauchau
Traunstein
Wiesmoor
Quedlinburg
Harburg
Plauen
Neu-Isenburg
Luetjenburg
Wiehl
Ochsenhausen
Hemhofen
Abenberg
Enz
Augsburg
Schmoelln
Coswig
Markkleeberg
(Wetterau)
Stadtroda
Muelheim-Kaerlich
Vilsbiburg
Wallenfels
Sigmaringen
Elzach
Schwarzenborn
(Schwaben)
Floeha
Metelen
Bautzen
Teupitz
Schalkau
Graefenhainichen
Wetzlar
Rodgau
Regis-Breitingen
Laasphe
Luedinghausen
Merseburg
Nittenau
Bietigheim-Bissingen
Vren
Hamm-Rhynern
Schmallenberg
Naunhof
Ruhland
Stein
Windischeschenbach
Schloss
Flensburg
Beckum
Gluecksburg
Lennestadt
Nagold
Treuchtlingen
Herrenberg
Landstuhl
Voer
Stadtsteinach
Arolsen
Obernkirchen
(Anhalt)
Wermelskirchen
Bevensen
Eggenfeln
Geyer
Stavenhagen
Leimen
Verl
Versmold
Neuenkirchen
Fritzlar
Landsberg
Reichenbach
Pirna
Friedrichsdorf
Reinheim
Blecke
Rehna
Hille
Monschau
Steinfurt)
Koenig
Lobenstein
(Mittelfranken)
Neuenahr-Ahrweiler
Elmshorn
Rennerod
Manrscheid
Uetersen
Gunsberg
Kaltenkirchen
Oebisfel-Weferlingen
Iserlohn
Wetter
Helmbrechts
Geilenkirchen
Tennstedt
Hilpoltstein
Todtnau
Kocher
Mirow
Rothenburg
Meersburg
Stemwe
Vaihingen
Gottleuba-Berggiesshuebel
Singen
Korntal-Muenchingen
Ahlen
Werben
Battenberg
Esens
Vetschau/Spreewald
Ostheim
Wunstorf
Traben-Trarbach
Neukirch/Lausitz
Riesa
(Gemuenn
Berching
Ober-Ramstadt
Heldrungen
Ahrensburg
Liebenwal
Sternberg
Rethem
Stuehlingen
Veln
Niddatal
Maulbronn
Eutin
Aach
Ludwigsstadt
Tettnang
Rostock
Kaarst
Meisenheim
Walrshof
Schwanebeck
Luebbenau/Spreewald
Ginsheim-Gustavsburg
Sachsen
Bacharach
Penig
Dillingen
(Geiseltal)
Mettmann
Penkun
Windsbach
Michelstadt
Zossen
(Nierlausitz)
Blomberg
Kolbermoor
Neuburg
Langenselbold
Sachsa
Augustdorf
Langenau
rdfs_label
Poessneck
par_open
Frankenau
Horstmar
Freren
Wanfried
Holzgerlingen
Nettetal
Grabfeld
Vacha
Bruehl
Daun
Norn
Putbus
(Dosse)
Leutkirch
Wurzen
Lotte
Stadtolndorf
Rosswein
Staufenberg
Aichtal
Krakow
Merzig
Werther
var_c
Marsberg
Markgroeningen
(Saale)
Orlamuen
(Taunus)
Kamenz
Neumuenster
Forchheim
Groitzsch
Lauingen
(Lausitz)
Kaisersesch
Leisnig
Viernheim
Harzgero
(Saalekreis)
Nidda
Ilshofen
Annweiler
Creglingen
Guesten
Petershagen
Blaubeuren
Waechtersbach
Brand-Erbisdorf
Oel
Zeven
Voelklingen
